// ═══════════════════════════════════════════════════════════
// CONSTANTS & CONFIGURATION
// Element variable names, resistance multiplier, and
// role-based stat ranges for fighters
// ═══════════════════════════════════════════════════════════
const EL_VAR={Spectro:'--Spectro',Havoc:'--Havoc',Aero:'--Aero',Glacio:'--Glacio',Electro:'--Electro',Fusion:'--Fusion',Physical:'--Physical'};
const RESISTANCE=0.9;

const ROLE_ST={
  dps:    {hp:[300,320], atk:[70,80],  def:[30,35]},
  subdps: {hp:[400,420], atk:[55,65],  def:[50,60]},
  support:{hp:[500,520], atk:[20,25],  def:[90,100]},
};

const WEAPON_IC={Sword:"🗡️",Broadblade:"🔱",Gauntlets:"👊",Pistol:"🔫",Rectifier:"📡"};

// ═══════════════════════════════════════════════════════════
// RESONATOR ROSTER
// Full list of all playable characters with their element,
// role (dps/subdps/support), emoji avatar, and weapon type
// ═══════════════════════════════════════════════════════════
const RESONATORS=[
  {name:"Rover (Spectro)", el:"Spectro", role:"support", emoji:"🌟", weapon:"Sword"},
  {name:"Rover (Havoc)",   el:"Havoc",   role:"dps",     emoji:"💜", weapon:"Sword"},
  {name:"Jiyan",           el:"Aero",    role:"dps",     emoji:"🌪️", weapon:"Broadblade"},
  {name:"Calcharo",        el:"Electro", role:"dps",     emoji:"⚡", weapon:"Sword"},
  {name:"Encore",          el:"Fusion",  role:"dps",     emoji:"🔥", weapon:"Rectifier"},
  {name:"Jianxin",         el:"Aero",    role:"subdps",  emoji:"🌬️", weapon:"Gauntlets"},
  {name:"Lingyang",        el:"Glacio",  role:"dps",     emoji:"❄️", weapon:"Gauntlets"},
  {name:"Verina",          el:"Spectro", role:"support", emoji:"✨", weapon:"Rectifier"},
  {name:"Aalto",           el:"Aero",    role:"subdps",  emoji:"🍃", weapon:"Pistol"},
  {name:"Baizhi",          el:"Glacio",  role:"support", emoji:"🌿", weapon:"Rectifier"},
  {name:"Chixia",          el:"Fusion",  role:"dps",     emoji:"🔫", weapon:"Pistol"},
  {name:"Danjin",          el:"Havoc",   role:"subdps",  emoji:"🗡️", weapon:"Sword"},
  {name:"Mortefi",         el:"Fusion",  role:"subdps",  emoji:"🎯", weapon:"Pistol"},
  {name:"Sanhua",          el:"Glacio",  role:"subdps",  emoji:"🌨️", weapon:"Sword"},
  {name:"Taoqi",           el:"Havoc",   role:"support", emoji:"🛡️", weapon:"Broadblade"},
  {name:"Yangyang",        el:"Aero",    role:"subdps",  emoji:"🎐", weapon:"Sword"},
  {name:"Yuanwu",          el:"Electro", role:"support", emoji:"🥊", weapon:"Broadblade"},
  {name:"Jinhsi",          el:"Spectro", role:"dps",     emoji:"💫", weapon:"Broadblade"},
  {name:"Changli",         el:"Fusion",  role:"subdps",  emoji:"🌋", weapon:"Sword"},
  {name:"Xiangli Yao",     el:"Electro", role:"dps",     emoji:"⚖️", weapon:"Gauntlets"},
  {name:"Zhezhi",          el:"Glacio",  role:"subdps",  emoji:"🧊", weapon:"Rectifier"},
  {name:"Shorekeeper",     el:"Spectro", role:"support", emoji:"🌊", weapon:"Rectifier"},
  {name:"Youhu",           el:"Glacio",  role:"support", emoji:"🦊", weapon:"Sword"},
  {name:"Camellya",        el:"Havoc",   role:"dps",     emoji:"🌸", weapon:"Sword"},
  {name:"Lumi",            el:"Electro", role:"subdps",  emoji:"💡", weapon:"Rectifier"},
  {name:"Carlotta",        el:"Glacio",  role:"dps",     emoji:"🔮", weapon:"Pistol"},
  {name:"Roccia",          el:"Havoc",   role:"subdps",  emoji:"🪨", weapon:"Gauntlets"},
  {name:"Phoebe",          el:"Spectro", role:"subdps",  emoji:"🌙", weapon:"Rectifier"},
  {name:"Brant",           el:"Havoc",   role:"support", emoji:"💀", weapon:"Sword"},
  {name:"Cantarella",      el:"Havoc",   role:"support", emoji:"🎭", weapon:"Sword"},
  {name:"Rover (Aero)",    el:"Aero",    role:"support", emoji:"🌬️", weapon:"Sword"},
  {name:"Zani",            el:"Spectro", role:"dps",     emoji:"👊", weapon:"Gauntlets"},
  {name:"Ciaccona",        el:"Aero",    role:"subdps",  emoji:"🎵", weapon:"Rectifier"},
  {name:"Cartethyia",      el:"Aero",    role:"dps",     emoji:"🌺", weapon:"Broadblade"},
  {name:"Lupa",            el:"Fusion",  role:"dps",     emoji:"🐺", weapon:"Broadblade"},
  {name:"Phrolova",        el:"Havoc",   role:"dps",     emoji:"🦅", weapon:"Broadblade"},
  {name:"Augusta",         el:"Electro", role:"dps",     emoji:"👑", weapon:"Broadblade"},
  {name:"Iuno",            el:"Aero",    role:"subdps",  emoji:"🎪", weapon:"Pistol"},
  {name:"Galbrena",        el:"Fusion",  role:"dps",     emoji:"⚔️", weapon:"Broadblade"},
  {name:"Qiuyuan",         el:"Aero",    role:"subdps",  emoji:"🍂", weapon:"Sword"},
  {name:"Chisa",           el:"Havoc",   role:"support", emoji:"🌀", weapon:"Sword"},
  {name:"Buling",          el:"Electro", role:"support", emoji:"⚡", weapon:"Rectifier"},
  {name:"Lynae",           el:"Spectro", role:"subdps",  emoji:"🌿", weapon:"Sword"},
  {name:"Mornye",          el:"Fusion",  role:"support", emoji:"🌾", weapon:"Rectifier"},
  {name:"Aemeath",         el:"Fusion",  role:"dps",     emoji:"🔱", weapon:"Sword"},
  {name:"Luuk Herssen",    el:"Spectro", role:"dps",     emoji:"🗡️", weapon:"Broadblade"},
];

// ═══════════════════════════════════════════════════════════
// CHARACTER CARD POOLS (CHAR_CARDS)
// Each resonator's unique set of cards: attack, heal, defend,
// buff, debuff. Each card has: name(n), type(t), icon(ic),
// value(v), cost(c), and optional ult/variety flags + vfx
// ═══════════════════════════════════════════════════════════
const CHAR_CARDS={
  "Rover (Spectro)":[
    {n:"Soul Link",    t:"heal",   ic:"🌟",v:55,c:2},
    {n:"Light Veil",   t:"defend", ic:"🛡️",v:85,c:2},
    {n:"Resonance",    t:"buff",   ic:"✨",bv:.08,c:1},
    {n:"Luminary",     t:"heal",   ic:"💫",v:80,c:3},
    {n:"Starweave",    t:"defend", ic:"🌟",v:125,c:3,ult:true},
    {n:"Star Fragment",t:"buff",ic:"🌠",bv:0.08,c:2,variety:true,vfx:"buff_allallies"},
  ],
  "Rover (Havoc)":[
    {n:"Void Slash",   t:"attack", ic:"💜",v:62,c:2},
    {n:"Rend",         t:"attack", ic:"🌑",v:52,c:1},
    {n:"Dark Wave",    t:"attack", ic:"🌀",v:90,c:2},
    {n:"Havoc Buff",   t:"buff",   ic:"💢",bv:.08,c:1},
    {n:"Cataclysm",    t:"attack", ic:"💥",v:125,c:3,ult:true},
    {n:"Void Devour",  t:"attack", ic:"🌑",v:72,c:2,variety:true,vfx:"consume_buff"},
  ],
  "Jiyan":[
    {n:"Gale Cleave",  t:"attack", ic:"🌪️",v:65,c:2},
    {n:"Wind Rush",    t:"attack", ic:"💨",v:52,c:1},
    {n:"Storm Break",  t:"attack", ic:"🌊",v:90,c:2},
    {n:"Tailwind",     t:"buff",   ic:"🎐",bv:.07,c:1},
    {n:"Qingloong",    t:"attack", ic:"🐉",v:128,c:3,ult:true},
    {n:"Dragon Spiral",t:"attack", ic:"🐉",v:76,c:2,variety:true,vfx:"self_shield_40"},
  ],
  "Calcharo":[
    {n:"Wuthering",    t:"attack", ic:"⚡",v:60,c:2},
    {n:"Resonator",    t:"attack", ic:"🌩️",v:50,c:1},
    {n:"Deathblade",   t:"attack", ic:"💀",v:88,c:2},
    {n:"Charge Up",    t:"buff",   ic:"🔋",bv:.09,c:1},
    {n:"Soulrend",     t:"attack", ic:"⚡",v:122,c:3,ult:true},
    {n:"Death Sentence",t:"attack",ic:"💀",v:80,c:2,variety:true,vfx:"execute_25"},
  ],
  "Encore":[
    {n:"Flaming Lamb", t:"attack", ic:"🔥",v:58,c:2},
    {n:"Wooly Atk",    t:"attack", ic:"🐑",v:51,c:1},
    {n:"Infernal",     t:"attack", ic:"🌋",v:85,c:2},
    {n:"Burning Soul", t:"buff",   ic:"♨️",bv:.10,c:2},
    {n:"Cosmos",       t:"attack", ic:"☄️",v:130,c:3,ult:true},
    {n:"Woolly Inferno",t:"attack",ic:"🐑",v:75,c:2,variety:true,vfx:"burn_dot_20"},
  ],
  "Jianxin":[
    {n:"Taichi Fist",  t:"attack", ic:"🌬️",v:55,c:2},
    {n:"Wind Jab",     t:"attack", ic:"💨",v:50,c:1},
    {n:"Barrier",      t:"defend", ic:"🛡️",v:80,c:2},
    {n:"Focus",        t:"buff",   ic:"🧘",bv:.06,c:1},
    {n:"Abyssal",      t:"attack", ic:"🌀",v:120,c:3,ult:true},
    {n:"Qi Absorption",t:"buff",   ic:"🌬️",bv:0.07,c:1,variety:true,vfx:"heal_self_30"},
  ],
  "Lingyang":[
    {n:"Lion Fist",    t:"attack", ic:"❄️",v:58,c:2},
    {n:"Ice Dash",     t:"attack", ic:"🧊",v:51,c:1},
    {n:"Blizzard",     t:"attack", ic:"🌨️",v:85,c:2},
    {n:"Frost Guard",  t:"defend", ic:"🛡️",v:76,c:1},
    {n:"Mythical",     t:"attack", ic:"🦁",v:124,c:3,ult:true},
    {n:"Mythical Pounce",t:"attack",ic:"🦁",v:58,c:1,variety:true,vfx:"none"},
  ],
  "Verina":[
    {n:"Heal Bloom",   t:"heal",   ic:"🌿",v:58,c:2},
    {n:"Petal Toss",   t:"defend", ic:"🌸",v:78,c:1},
    {n:"Verdant Chain",t:"heal",   ic:"💚",v:82,c:3},
    {n:"Nature Veil",  t:"buff",   ic:"🌱",bv:.07,c:1},
    {n:"Arboretum",    t:"heal",   ic:"🌳",v:125,c:3,ult:true},
    {n:"Verdant Overgrowth",t:"heal",ic:"🌺",v:90,c:2,variety:true,vfx:"shield_all_40"},
  ],
  "Aalto":[
    {n:"Fog Blade",    t:"attack", ic:"🍃",v:52,c:2},
    {n:"Mist Step",    t:"attack", ic:"💨",v:50,c:1},
    {n:"Gust Barrage", t:"attack", ic:"🌪️",v:80,c:2},
    {n:"Smokescreen",  t:"debuff", ic:"🌫️",dv:0.2,c:2},
    {n:"Mistwalker",   t:"attack", ic:"🌬️",v:121,c:3,ult:true},
    {n:"Vanishing Act",t:"debuff", ic:"🌫️",dv:0.20,c:2,variety:true,vfx:"untargetable"},
  ],
  "Baizhi":[
    {n:"Healing Wind", t:"heal",   ic:"🌿",v:55,c:2},
    {n:"Herb Shield",  t:"defend", ic:"🌱",v:76,c:1},
    {n:"Verdant Burst",t:"heal",   ic:"💚",v:82,c:3},
    {n:"Barrier Bloom",t:"defend", ic:"🌳",v:95,c:2},
    {n:"Eternal Bloom",t:"heal",   ic:"🌸",v:122,c:3,ult:true},
    {n:"Glacial Blossom",t:"heal", ic:"🌸",v:75,c:2,variety:true,vfx:"shield_lowest_50"},
  ],
  "Chixia":[
    {n:"Fire Shot",    t:"attack", ic:"🔫",v:56,c:2},
    {n:"Quick Draw",   t:"attack", ic:"💥",v:51,c:1},
    {n:"Inferno Shot", t:"attack", ic:"🔥",v:84,c:2},
    {n:"Heat Up",      t:"buff",   ic:"♨️",bv:.08,c:1},
    {n:"Blazing Rain", t:"attack", ic:"🌋",v:127,c:3,ult:true},
    {n:"Burst Fire",   t:"attack", ic:"🔫",v:60,c:2,variety:true,vfx:"double_hit_50"},
  ],
  "Danjin":[
    {n:"Bloody Slash", t:"attack", ic:"🗡️",v:62,c:2},
    {n:"Quick Slice",  t:"attack", ic:"⚔️",v:51,c:1},
    {n:"Crimson Tide", t:"debuff", ic:"🩸",dv:0.22,c:2},
    {n:"Blood Pact",   t:"buff",   ic:"💢",bv:.10,c:2},
    {n:"Vermillion",   t:"attack", ic:"🔱",v:123,c:3,ult:true},
    {n:"Life Drain",   t:"attack", ic:"🩸",v:62,c:2,variety:true,vfx:"lifesteal_40"},
  ],
  "Mortefi":[
    {n:"Flame Arc",    t:"attack", ic:"🎯",v:54,c:2},
    {n:"Ember",        t:"attack", ic:"🔥",v:50,c:1},
    {n:"Ignition",     t:"debuff", ic:"☠️",dv:0.18,c:2},
    {n:"Overheat",     t:"buff",   ic:"♨️",bv:.09,c:1},
    {n:"Conflagrate",  t:"attack", ic:"🌋",v:126,c:3,ult:true},
    {n:"Detonation Mark",t:"debuff",ic:"💣",dv:0.18,c:2,variety:true,vfx:"delayed_debuff"},
  ],
  "Sanhua":[
    {n:"Ice Prison",   t:"attack", ic:"🌨️",v:54,c:2},
    {n:"Cold Snap",    t:"attack", ic:"❄️",v:50,c:1},
    {n:"Cryo Lock",    t:"debuff", ic:"🔒",dv:0.2,c:2},
    {n:"Glacial Guard",t:"defend", ic:"🛡️",v:80,c:2},
    {n:"Eternal Frost",t:"attack", ic:"🧊",v:122,c:3,ult:true},
    {n:"Zero Point",   t:"attack", ic:"🌡️",v:70,c:2,variety:true,vfx:"bonus_debuffed_30"},
  ],
  "Taoqi":[
    {n:"Block",        t:"defend", ic:"🛡️",v:90,c:2},
    {n:"Great Wall",   t:"defend", ic:"🏯",v:110,c:2},
    {n:"Taunt",        t:"buff",   ic:"📣",bv:.06,c:1},
    {n:"Iron Heal",    t:"heal",   ic:"💚",v:52,c:1},
    {n:"Unbreakable",  t:"defend", ic:"⛰️",v:130,c:3,ult:true},
    {n:"Iron Fortress",t:"defend", ic:"🏯",v:120,c:2,variety:true,vfx:"shield_all_split"},
  ],
  "Yangyang":[
    {n:"Wind Dance",   t:"attack", ic:"🎐",v:52,c:2},
    {n:"Feather Slash",t:"attack", ic:"🪶",v:50,c:1},
    {n:"Sky Rend",     t:"debuff", ic:"🌤️",dv:0.18,c:2},
    {n:"Gale Step",    t:"buff",   ic:"💨",bv:.07,c:1},
    {n:"Stormwing",    t:"attack", ic:"🌪️",v:120,c:3,ult:true},
    {n:"Gale Cry",     t:"attack", ic:"🪶",v:52,c:1,variety:true,vfx:"target_lowest_hp"},
  ],
  "Yuanwu":[
    {n:"Iron Body",    t:"defend", ic:"🛡️",v:88,c:2},
    {n:"Thunder Guard",t:"defend", ic:"⚡",v:105,c:2},
    {n:"Rally",        t:"buff",   ic:"📯",bv:.06,c:1},
    {n:"Volt Heal",    t:"heal",   ic:"💚",v:50,c:1},
    {n:"Thunderclad",  t:"defend", ic:"⛈️",v:128,c:3,ult:true},
    {n:"Thunderclap Aura",t:"defend",ic:"⚡",v:100,c:2,variety:true,vfx:"shield_mini_all_25"},
  ],
  "Jinhsi":[
    {n:"Stellar Strike",t:"attack",ic:"💫",v:65,c:2},
    {n:"Radiance",      t:"attack",ic:"🌟",v:52,c:1},
    {n:"Blazing Sun",   t:"attack",ic:"☀️",v:90,c:2},
    {n:"Illuminate",    t:"buff",  ic:"✨",bv:.09,c:1},
    {n:"Incarnation",   t:"attack",ic:"🌞",v:129,c:3,ult:true},
    {n:"Incandescent Mark",t:"attack",ic:"☀️",v:78,c:2,variety:true,vfx:"mark_plus15_dmg"},
  ],
  "Changli":[
    {n:"Flame Burst",  t:"attack", ic:"🔥",v:58,c:2},
    {n:"Ember Shot",   t:"attack", ic:"💥",v:50,c:1},
    {n:"Inferno Wave", t:"debuff", ic:"☠️",dv:0.22,c:2},
    {n:"Burn Mark",    t:"buff",   ic:"♨️",bv:.08,c:1},
    {n:"True Sight",   t:"attack", ic:"🌋",v:125,c:3,ult:true},
    {n:"Truthseeker Flame",t:"attack",ic:"🔱",v:72,c:2,variety:true,vfx:"bonus_buffed_25pct"},
  ],
  "Xiangli Yao":[
    {n:"Thunderclap",  t:"attack", ic:"⚡",v:60,c:2},
    {n:"Chain Bolt",   t:"attack", ic:"🔗",v:51,c:1},
    {n:"Judge Strike", t:"attack", ic:"⚖️",v:88,c:2},
    {n:"Electro Field",t:"buff",   ic:"🌐",bv:.08,c:1},
    {n:"Verdict",      t:"attack", ic:"⚖️",v:122,c:3,ult:true},
    {n:"Final Verdict",t:"attack", ic:"⚖️",v:85,c:2,variety:true,vfx:"bonus_shield_20pct"},
  ],
  "Zhezhi":[
    {n:"Brushstroke",  t:"attack", ic:"🧊",v:54,c:2},
    {n:"Ink Frost",    t:"attack", ic:"❄️",v:50,c:1},
    {n:"Cryo Canvas",  t:"debuff", ic:"🖼️",dv:0.2,c:2},
    {n:"Ice Veil",     t:"defend", ic:"🛡️",v:80,c:2},
    {n:"Masterpiece",  t:"attack", ic:"🎨",v:124,c:3,ult:true},
    {n:"Living Painting",t:"attack",ic:"🎨",v:65,c:2,variety:true,vfx:"random_target_debuff10"},
  ],
  "Shorekeeper":[
    {n:"Tidal Wave",   t:"heal",   ic:"🌊",v:58,c:2},
    {n:"Sea Pulse",    t:"defend", ic:"💧",v:78,c:1},
    {n:"Abyss Call",   t:"buff",   ic:"🌑",bv:.07,c:1},
    {n:"Barrier Reef", t:"defend", ic:"🛡️",v:105,c:2},
    {n:"Revelation",   t:"heal",   ic:"🌊",v:120,c:3,ult:true},
    {n:"Abyssal Lullaby",t:"defend",ic:"🌊",v:110,c:2,variety:true,vfx:"shield_lowest_def"},
  ],
  "Youhu":[
    {n:"Ice Guard",    t:"defend", ic:"🦊",v:88,c:2},
    {n:"Frost Aura",   t:"buff",   ic:"❄️",bv:.07,c:1},
    {n:"Cryo Shield",  t:"defend", ic:"🛡️",v:105,c:2},
    {n:"Tail Whip",    t:"heal",   ic:"💚",v:52,c:1},
    {n:"Arctic Fox",   t:"defend", ic:"🌨️",v:126,c:3,ult:true},
    {n:"Spirit Fox Ward",t:"defend",ic:"🦊",v:80,c:1,variety:true,vfx:"none"},
  ],
  "Camellya":[
    {n:"Petal Storm",  t:"attack", ic:"🌸",v:62,c:2},
    {n:"Vine Lash",    t:"attack", ic:"🌿",v:51,c:1},
    {n:"Bloom Burst",  t:"attack", ic:"💐",v:88,c:2},
    {n:"Dark Bloom",   t:"debuff", ic:"☠️",dv:0.22,c:2},
    {n:"Elegy",        t:"attack", ic:"🌺",v:128,c:3,ult:true},
    {n:"Elegy Thorns", t:"attack", ic:"🌺",v:55,c:1,variety:true,vfx:"none"},
  ],
  "Lumi":[
    {n:"Volt Shot",    t:"attack", ic:"💡",v:52,c:2},
    {n:"Spark",        t:"attack", ic:"⚡",v:50,c:1},
    {n:"Surge",        t:"debuff", ic:"🌩️",dv:0.18,c:2},
    {n:"Amp Up",       t:"buff",   ic:"🔋",bv:.08,c:1},
    {n:"Overload",     t:"attack", ic:"💥",v:120,c:3,ult:true},
    {n:"Feedback Loop",t:"buff",   ic:"🔋",bv:0.08,c:1,variety:true,vfx:"draw_extra_card"},
  ],
  "Carlotta":[
    {n:"Ice Bullet",   t:"attack", ic:"🔮",v:58,c:2},
    {n:"Frost Shot",   t:"attack", ic:"❄️",v:50,c:1},
    {n:"Crystal Rain", t:"attack", ic:"💎",v:85,c:2},
    {n:"Chill Aura",   t:"buff",   ic:"🌡️",bv:.08,c:1},
    {n:"Blizzard",     t:"attack", ic:"🧊",v:123,c:3,ult:true},
    {n:"Glass Coffin", t:"attack", ic:"💎",v:82,c:2,variety:true,vfx:"refund_on_kill"},
  ],
  "Roccia":[
    {n:"Rock Slam",    t:"attack", ic:"🪨",v:62,c:2},
    {n:"Pebble Toss",  t:"attack", ic:"💜",v:51,c:1},
    {n:"Gravity Crash",t:"debuff", ic:"🌑",dv:0.2,c:2},
    {n:"Stone Wall",   t:"defend", ic:"🛡️",v:82,c:2},
    {n:"Avalanche",    t:"attack", ic:"🏔️",v:126,c:3,ult:true},
    {n:"Tectonic Shatter",t:"debuff",ic:"🪨",dv:0.20,c:2,variety:true,vfx:"shatter_highdef_15"},
  ],
  "Phoebe":[
    {n:"Moonray",      t:"attack", ic:"🌙",v:54,c:2},
    {n:"Star Dust",    t:"attack", ic:"⭐",v:50,c:1},
    {n:"Lunar Veil",   t:"debuff", ic:"🌑",dv:0.18,c:2},
    {n:"Moonveil",     t:"defend", ic:"🛡️",v:76,c:1},
    {n:"Eclipse",      t:"attack", ic:"🌑",v:121,c:3,ult:true},
    {n:"Crescent Omen",t:"attack", ic:"🌙",v:70,c:2,variety:true,vfx:"target_highest_hp"},
  ],
  "Brant":[
    {n:"Dirge",        t:"heal",   ic:"💀",v:54,c:2},
    {n:"Soul Guard",   t:"defend", ic:"🛡️",v:78,c:1},
    {n:"Pale Veil",    t:"defend", ic:"🌫️",v:100,c:2},
    {n:"Grim Pact",    t:"buff",   ic:"🔱",bv:.07,c:1},
    {n:"Requiem",      t:"heal",   ic:"🎼",v:124,c:3,ult:true},
    {n:"Death's Bargain",t:"buff", ic:"💀",bv:0.08,c:2,variety:true,vfx:"buff_lowest_hp_ally"},
  ],
  "Cantarella":[
    {n:"Waltz Shield", t:"defend", ic:"🎭",v:88,c:2},
    {n:"Masked Step",  t:"heal",   ic:"🎪",v:52,c:1},
    {n:"Veil",         t:"defend", ic:"🌫️",v:100,c:2},
    {n:"Venom Pact",   t:"buff",   ic:"☠️",bv:.07,c:1},
    {n:"Finale",       t:"heal",   ic:"🎇",v:126,c:3,ult:true},
    {n:"Masquerade Poison",t:"debuff",ic:"🎭",dv:0.18,c:1,variety:true,vfx:"target_lowest_hppct"},
  ],
  "Rover (Aero)":[
    {n:"Wind Guard",   t:"defend", ic:"🌬️",v:85,c:2},
    {n:"Aero Heal",    t:"heal",   ic:"💨",v:52,c:1},
    {n:"Sky Barrier",  t:"defend", ic:"🛡️",v:105,c:2},
    {n:"Gale Buff",    t:"buff",   ic:"🎐",bv:.07,c:1},
    {n:"Tempest Veil", t:"defend", ic:"🌪️",v:130,c:3,ult:true},
    {n:"Tailwind Blessing",t:"buff",ic:"🌬️",bv:0.08,c:2,variety:true,vfx:"buff_allallies"},
  ],
  "Zani":[
    {n:"Spectral Fist",t:"attack", ic:"👊",v:60,c:2},
    {n:"Ghost Jab",    t:"attack", ic:"👻",v:51,c:1},
    {n:"Phantom Rush", t:"attack", ic:"💫",v:85,c:2},
    {n:"Spirit Guard", t:"buff",   ic:"✨",bv:.08,c:1},
    {n:"Oblivion",     t:"attack", ic:"🌑",v:122,c:3,ult:true},
    {n:"Ghost Step",   t:"debuff", ic:"👻",dv:0.20,c:1,variety:true,vfx:"ignore_shield"},
  ],
  "Ciaccona":[
    {n:"Music Blade",  t:"attack", ic:"🎵",v:52,c:2},
    {n:"Note Strike",  t:"attack", ic:"🎶",v:50,c:1},
    {n:"Cadence",      t:"debuff", ic:"🎼",dv:0.18,c:2},
    {n:"Harmony",      t:"buff",   ic:"🎸",bv:.07,c:1},
    {n:"Symphony",     t:"attack", ic:"🎺",v:120,c:3,ult:true},
    {n:"Resonant Frequency",t:"debuff",ic:"🎵",dv:0.18,c:2,variety:true,vfx:"remove_top_card"},
  ],
  "Cartethyia":[
    {n:"Petal Slash",  t:"attack", ic:"🌺",v:54,c:2},
    {n:"Wind Kiss",    t:"attack", ic:"💨",v:50,c:1},
    {n:"Blossom Storm",t:"attack", ic:"🌸",v:82,c:2},
    {n:"Gentle Breeze",t:"buff",   ic:"🎐",bv:.07,c:1},
    {n:"Flowering",    t:"attack", ic:"🌻",v:124,c:3,ult:true},
    {n:"Petal Tempest",t:"attack", ic:"🌺",v:72,c:2,variety:true,vfx:"splash_second_40pct"},
  ],
  "Lupa":[
    {n:"Wolf Fang",    t:"attack", ic:"🐺",v:62,c:2},
    {n:"Pack Howl",    t:"attack", ic:"🌙",v:51,c:1},
    {n:"Alpha Strike", t:"attack", ic:"⚔️",v:88,c:2},
    {n:"Fury",         t:"buff",   ic:"🔥",bv:.10,c:2},
    {n:"Bloodlust",    t:"attack", ic:"🩸",v:130,c:3,ult:true},
    {n:"Pack Frenzy",  t:"buff",   ic:"🐺",bv:0.08,c:2,variety:true,vfx:"buff_top2_atk"},
  ],
  "Phrolova":[
    {n:"Dark Talon",   t:"attack", ic:"🦅",v:62,c:2},
    {n:"Dive",         t:"attack", ic:"💨",v:51,c:1},
    {n:"Shred",        t:"debuff", ic:"☠️",dv:0.25,c:2},
    {n:"Predator",     t:"buff",   ic:"🔥",bv:.09,c:1},
    {n:"Storm Dive",   t:"attack", ic:"🌑",v:125,c:3,ult:true},
    {n:"Apex Predator",t:"attack", ic:"🦅",v:80,c:2,variety:true,vfx:"target_highest_atk"},
  ],
  "Augusta":[
    {n:"Crown Strike", t:"attack", ic:"👑",v:60,c:2},
    {n:"Zap",          t:"attack", ic:"⚡",v:51,c:1},
    {n:"Royal Arc",    t:"attack", ic:"🌩️",v:88,c:2},
    {n:"Sovereign",    t:"buff",   ic:"🏆",bv:.10,c:1},
    {n:"Dominion",     t:"attack", ic:"👑",v:128,c:3,ult:true},
    {n:"Sovereign Decree",t:"debuff",ic:"👑",dv:0.20,c:2,variety:true,vfx:"debuff_all_enemies"},
  ],
  "Iuno":[
    {n:"Aero Jab",     t:"attack", ic:"🎪",v:52,c:2},
    {n:"Gust",         t:"attack", ic:"💨",v:50,c:1},
    {n:"Wind Debuff",  t:"debuff", ic:"🌀",dv:0.18,c:2},
    {n:"Breeze Buff",  t:"buff",   ic:"🎐",bv:.07,c:1},
    {n:"Cyclone",      t:"attack", ic:"🌪️",v:120,c:3,ult:true},
    {n:"Aerial Ambush",t:"attack", ic:"🎪",v:66,c:2,variety:true,vfx:"target_lowest_def"},
  ],
  "Galbrena":[
    {n:"Flame Blade",  t:"attack", ic:"⚔️",v:62,c:2},
    {n:"Fire Jab",     t:"attack", ic:"🔥",v:51,c:1},
    {n:"Inferno Cut",  t:"attack", ic:"🌋",v:88,c:2},
    {n:"War Cry",      t:"buff",   ic:"📯",bv:.10,c:1},
    {n:"Reckoning",    t:"attack", ic:"⚡",v:127,c:3,ult:true},
    {n:"Battle Veteran",t:"attack",ic:"⚔️",v:60,c:1,variety:true,vfx:"scale_hp_pct"},
  ],
  "Qiuyuan":[
    {n:"Autumn Blade", t:"attack", ic:"🍂",v:52,c:2},
    {n:"Leaf Dart",    t:"attack", ic:"🍃",v:50,c:1},
    {n:"Wind Scar",    t:"debuff", ic:"🌬️",dv:0.18,c:2},
    {n:"Harvest",      t:"buff",   ic:"🌾",bv:.07,c:1},
    {n:"Last Leaf",    t:"attack", ic:"🍁",v:121,c:3,ult:true},
    {n:"Autumn Reckoning",t:"buff",ic:"🌾",bv:0.07,c:1,variety:true,vfx:"stacking_buff"},
  ],
  "Chisa":[
    {n:"Vortex Guard", t:"defend", ic:"🌀",v:88,c:2},
    {n:"Dark Heal",    t:"heal",   ic:"💜",v:52,c:1},
    {n:"Abyss Shield", t:"defend", ic:"🛡️",v:105,c:2},
    {n:"Shadow Buff",  t:"buff",   ic:"🌑",bv:.07,c:1},
    {n:"Abyss",        t:"defend", ic:"🌀",v:128,c:3,ult:true},
    {n:"Null Vortex",  t:"defend", ic:"🌀",v:105,c:2,variety:true,vfx:"reduce_next_hit_20"},
  ],
  "Buling":[
    {n:"Static Guard", t:"defend", ic:"⚡",v:85,c:2},
    {n:"Volt Heal",    t:"heal",   ic:"💚",v:52,c:1},
    {n:"Surge Shield", t:"defend", ic:"🛡️",v:105,c:2},
    {n:"Charge Buff",  t:"buff",   ic:"🔋",bv:.06,c:1},
    {n:"Overcharge",   t:"heal",   ic:"💡",v:120,c:3,ult:true},
    {n:"Overcharge Field",t:"heal",ic:"⚡",v:68,c:2,variety:true,vfx:"restore_1_energy"},
  ],
  "Lynae":[
    {n:"Spectro Blade",t:"attack", ic:"🌿",v:52,c:2},
    {n:"Vine Strike",  t:"attack", ic:"🍃",v:50,c:1},
    {n:"Root Debuff",  t:"debuff", ic:"🌱",dv:0.2,c:2},
    {n:"Nature Buff",  t:"buff",   ic:"🌳",bv:.08,c:1},
    {n:"Overgrowth",   t:"attack", ic:"🌲",v:122,c:3,ult:true},
    {n:"Nature's Wrath",t:"attack",ic:"🌿",v:68,c:2,variety:true,vfx:"bonus_def_scaling"},
  ],
  "Mornye":[
    {n:"Harvest Heal", t:"heal",   ic:"🌾",v:58,c:2},
    {n:"Crop Shield",  t:"defend", ic:"🛡️",v:78,c:1},
    {n:"Abundance",    t:"heal",   ic:"💚",v:82,c:3},
    {n:"Blessing",     t:"buff",   ic:"✨",bv:.07,c:1},
    {n:"Bounty",       t:"heal",   ic:"🌟",v:123,c:3,ult:true},
    {n:"Abundant Harvest",t:"heal",ic:"🌾",v:65,c:2,variety:true,vfx:"heal_two_lowest"},
  ],
  "Aemeath":[
    {n:"Flame Cross",  t:"attack", ic:"🔱",v:62,c:2},
    {n:"Sacred Fire",  t:"attack", ic:"🔥",v:51,c:1},
    {n:"Holy Blaze",   t:"attack", ic:"✝️",v:88,c:2},
    {n:"Devotion",     t:"buff",   ic:"✨",bv:.10,c:1},
    {n:"Revelation",   t:"attack", ic:"🌟",v:120,c:3,ult:true},
    {n:"Divine Immolation",t:"attack",ic:"✝️",v:90,c:2,variety:true,vfx:"self_damage_20"},
  ],
  "Luuk Herssen":[
    {n:"Spectro Blade",t:"attack", ic:"🗡️",v:62,c:2},
    {n:"Quick Slash",  t:"attack", ic:"⚡",v:51,c:1},
    {n:"Void Edge",    t:"attack", ic:"💫",v:88,c:2},
    {n:"Battle Cry",   t:"buff",   ic:"📯",bv:.09,c:1},
    {n:"Annihilation", t:"attack", ic:"💥",v:129,c:3,ult:true},
    {n:"Spectral Execution",t:"attack",ic:"💀",v:85,c:2,variety:true,vfx:"execute_30"},
  ],
};

